Subscription Group Signup docs
maxio-com/stoplight-platform-api-docs pull request #159
Opened 2022-12-01 12:02 UTC by sbulat

We have a possibility to create a Subscription group with subscription attributes passed - it will create each subscription and put them in one group. Recently, we improved this functionality and we want to separate that into another endpoint (https://github.com/maxio-com/chargify/pull/22122).

This PR documents all the properties you can pass to Subscription Group Signup.
Simultaneously with this PR, we will remove the Feature Flag (this work is not ready yet).

2022-12-12 12:59 UTC, SzymonGibalski commented on reference/Chargify-API.v1.yaml
> +      operationId: post-subscription_groups_with_subs.j.json
```suggestion
      operationId: post-subscription_groups_with_subs.json
```

2022-12-12 14:31 UTC, pohor commented on reference/Chargify-API.v1.yaml
> +                          description: '(Optional when creating a subscription with GoCardless). International Bank Account Number. Alternatively, local bank details can be provided'
why is there a ` here? it's not in the other descriptions 🤔

2022-12-12 14:33 UTC, pohor requested changes
The formatting of `description` field differs in places. Some is between '' signs and other is not or starts with `. Could you please unify this 🙏 ?

2022-12-15 07:57 UTC, pohor approved these changes
🙌

2023-01-16 14:48 UTC, merged