Update OperationIds for human readable labels
maxio-com/stoplight-platform-api-docs pull request #185
Opened 2023-06-16 21:07 UTC by nestorsalinas88

Ticket:
https://maxioevolution.atlassian.net/browse/DE-312

Type of change:
 internal

What
This PR updates the OAS `operationId`s with human readable labels

How
operationId is optional property for an operation but it’s used for method names in generated SDK.

e.g. post-portal-customers-customer_id-enable.json → postPortalCustomersCustomerIdEnableJson - this name is complicated, is postfixed with Json and is meaningless. Better name would be e.g. enableBillingPortal.

So these operationIds need to be meaningful as they will be most visible and most used part in SDK.

2023-06-20 08:41 UTC, michalpierog requested changes

2023-06-20 08:41 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readWebhooks
Should we use readWebhooks or listWebhooks?
https://www.notion.so/maxioevolution/Our-Conventions-Stoplight-Studio-ddc9875ac9f743b1915eec6b37845fa0#8187f48fe9ac4a029a5f1d2b9896a709

> - For CRUD-related action words, use the following:
>     - Create (ie. Create Component)
>     - Read (ie. Read Component)
>     - Update (ie. Update Component)
>     - Delete (ie. Delete Component)
>     - List (ie. List Components)

2023-06-20 08:41 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readWebhookEndpoints
listEndpoints? I would keep this consistent, in other places we have `updateEndpoint`, `createEndpoint` instead of `updateWebhookEndpoint`, `createWebhookEndpoint`.

2023-06-20 08:41 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readSubscriptionNotes
listSubscriptionNotes?

2023-06-20 08:41 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readCustomers
We should decide if we want to use listXXXs or readXXXs.

2023-06-23 07:57 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readWebhookEndpoints
You forgot to rename to `listEndpoints`

2023-06-23 10:56 UTC, michalpierog requested changes

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSubscriptionComponentsAllocations
listAllocations

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionComponentsAllocations
allocateComponents

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionComponentsAllocationsPreview
previewAllocations

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> -      operationId: put-subscriptions-subscription_id-components-component_id-allocations-allocation_id-.json
updatePrepaidUsageAllocation?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionComponentUsage
Maybe shorter `createUsage`?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSubscriptionComponentsUsages
listUsages?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: activateSubscriptionEventBasedComponent
`activateEventBasedComponent` ?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: deactivateSubscriptionEventBasedComponent
`deactivateEventBasedComponent`?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSiteSubscriptions
listSubscriptions

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createEventBasedComponentEvent
`recordEvent`?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createEventBasedComponentEvents
recordEvents

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSiteOffers
listOffers

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSubscriptionsSalesCommission
listSalesCommissionSettings

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSalesRepDetails
listSalesReps?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSalesRepDetails
listSalesReps?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readSalesRepSubscriptions
readSalesRep?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: retrySubscriptionPayment
retrySubscription?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: automaticallyResumeSubscription
updateAutomaticSubscriptionResumption?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionProductMigration
migrateSubscriptionProduct

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionProductMigrationPreview
previewSubscriptionProductMigration

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: OverrideSubscription
overrideSubscription

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionDelayedCancellation
initiateDelayedCancellation

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: deleteSubscriptionDelayedCancellation
`stopDelayedCancellation`/`cancelDelayedCancellation`?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionDunningCancellation
cancelDunning

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionRenewalPreview
previewRenewal

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionAdhocInvoice
createInvoice

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionPrepayment
createPrepayment

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSubscriptionPrepayments
listPrepayments

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: issueSubscriptionSeviceCredit
issueServiceCredit

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: deductSubscriptionServiceCredit
deductServiceCredit

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionsInGroup
signupWithSubscriptionGroup?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSiteSubscriptionGroups
listSubscriptionGroups

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readSubscriptionGroupBySubscription
readSubscriptionGroupBySubscriptionId

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionGroupDelayedCancellations
initiateDelayedGroupCancellation/initiateDelayedCancellationForGroup

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: deleteSubscriptionGroupDelayedCancellation
`stopDelayedGroupCancellation`/`cancelDelayedGroupCancellation`/`stopDelayedCancellationForGroup`? Keep consistent with initiate method

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: deleteSubscriptionFromGroup
removeSubscriptionFromGroup?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionPreview
previewSubscription

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listChargifyJsKeys
listChargifyJsPublicKeys

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createConsolidatedSubscriptionProformaInvoice
createConsolidatedProformaInvoice

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: applySubscriptionCouponCodes
applyCouponToSubscription

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionProformaInvoice
createProformaInvoice

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSubscriptionProformaInvoices
listProformaInvoices

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionProformaInvoicePreview
previewProformaInvoice

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: deliverInvoiceEmail
sendInvoice

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: updateInvoiceCustomerDetails
previewCustomerInformationChanges

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: updateCustomerInformationForOpenInvoice
updateCustomerInformation

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSiteSubscriptionComponents
listSubscriptionComponentsForSite?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createComponentPricePointSegment
createSegment

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listComponentPricePointSegments
listSegmentsForPricePoint?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: updateComponentPricePointSegment
updateSegment

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: deleteComponentSegment
deleteSegment

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createComponentPricePointSegments
createSegments

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: updateComponentPricePointSegments
updateSegments

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: issueSubscriptionInvoiceInAdvance
issueAdvanceInvoice?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readSubscriptionUpcomingRenewalAdvanceInvoice
readAdvanceInvoice?

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: readSubscriptionLegacyMrr
listMrrPerSubscription

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: refundSubscriptionPrepayment
refundPrepayment

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSiteProducts
listProducts

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSiteComponentPricePoints
listComponentPricePoints

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSiteProductPricePoints
listProductPricePoints

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionSignupProformaInvoice
createSignupProformaInvoice

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionSignupProformaPreview
previewSignupProformaInvoice

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listProformaInvoicesRowsExport
listExportedProformaInvoices

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listInvoicesRowsExport
listExportedInvoices

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: listSubscriptionsExport
listExportedSubscriptions

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createProformaInvoicesExport
exportProformaInvoices

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createInvoicesExport
exportInvoices

2023-06-23 10:56 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: createSubscriptionsExport
exportSubscriptions

2023-06-23 10:57 UTC, michalpierog requested changes
Added some suggestions

2023-06-26 22:05 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: readComponentById
There are two endpoints documented both line:5151 readComponentByID and line:5091 readComponentByHandle. Let's circle back to this one

2023-06-26 22:10 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: createInvoicePayment
@himn1 any thoughts or preference?

2023-06-26 22:13 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: listConsolidatedInvoiceSegments
Keeping `listInvoiceSegments`

2023-06-26 22:15 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: createInvoicePayment
`recordPaymentForInvoice`

2023-06-26 22:16 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: createExternalInvoicesPayment
`recordExternalPaymentForInvoices` @himn1 any thoughts?

2023-06-26 22:27 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: deleteSubscriptionDelayedCancellation
@freezepl any preference? updating to `stopDelayedCancellation` for now

2023-06-27 14:03 UTC, freezepl commented
I agree with Michal. I think we should use `list` instead of `read`.

2023-06-27 14:05 UTC, michal-samluk commented on reference/Chargify-API.v1.yaml
> +      operationId: readCustomers
I vote for `list`

2023-06-27 15:35 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: readCustomers
updated to list `listCustomers`

2023-06-27 15:37 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: enableCustomerPortalAccess
Used `enableBillingPortalForCustomer`

2023-06-28 10:03 UTC, simonx1 requested changes
@nestorsalinas88 I went through the changes, they mostly look good to me.
I have one question (or probably change request though).

I've run into a couple of places where the `operationId` is changed to something that ends with `name-name-.json` (with the dash before `.json`), see here

```
                           return_params: engine=md7a
                           url: 'https://general-goods.chargify.com/subscribe/m6tbcq4mcgpw/no-cost-product'
                       product_price_point_name: Default
-      operationId: readProductByHandle
+      operationId: get-products-handle-api_handle-.json
       description: This method allows to retrieve a Product object by its `api_handle`.
   /product_families.json:
```
I assume the ID was somehow auto-generated to be unique, but I'm not sure if there should be a dash at the end of the name part.
WDYT?

2023-06-28 10:42 UTC, michalpierog commented
> @nestorsalinas88 I went through the changes, they mostly look good to me. I have one question (or probably change request though).
> 
> I've run into a couple of places where the `operationId` is changed to something that ends with `name-name-.json` (with the dash before `.json`), see here
> 
> ```
>                            return_params: engine=md7a
>                            url: 'https://general-goods.chargify.com/subscribe/m6tbcq4mcgpw/no-cost-product'
>                        product_price_point_name: Default
> -      operationId: readProductByHandle
> +      operationId: get-products-handle-api_handle-.json
>        description: This method allows to retrieve a Product object by its `api_handle`.
>    /product_families.json:
> ```
> 
> I assume the ID was somehow auto-generated to be unique, but I'm not sure if there should be a dash at the end of the name part. WDYT?

@simonx1 
this diff is showing something wrong. All operationIds were changed from format `do-something-xxx.json` to names like `doSomethingXxx` so after the change there would be readProductByHandle instead of `get-products-handle-api_handle-.json`
For some reason the diff you included shows it in the opposite way.

2023-06-28 12:56 UTC, michalpierog approved these changes
LGTM

2023-06-28 14:39 UTC, simonx1 approved these changes
LGTM, when the comments are resolved! 🚀

2023-06-29 12:30 UTC, freezepl commented on reference/Chargify-API.v1.yaml
> +      operationId: listSubscriptionsByCustomer
`listCustomerSubscriptions` is better.
If we would have more lists like `listSubscriptionsByProduct` or `listSubscriptionsByDate` then I would go with `listSubscriptionsByCustomer`

2023-06-29 12:30 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: readLegacyMrr
added the `deprecated: true` values on readMrr

2023-06-29 12:31 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: readLegacyMrrMovements
also included `deprecated: true` values

2023-06-29 12:36 UTC, nestorsalinas88 commented on reference/Chargify-API.v1.yaml
> +      operationId: deleteSubscriptionGroupDelayedCancellation
`stopDelayedCancellationForGroup`

2023-06-29 12:56 UTC, merged