In 1475 update chargify api documentation
maxio-com/stoplight-platform-api-docs pull request #186
Opened 2023-06-23 12:48 UTC by Lukasz-Ziemnicki

Reference: [IN-934](https://maxioevolution.atlassian.net/browse/IN-934)

New endpoint listing prepayments for a single subscription group.

https://github.com/maxio-com/stoplight-platform-api-docs/assets/52356982/858e8770-5983-4191-bbd5-858645e3c8cf

2023-07-05 14:47 UTC, ardahaal approved these changes
🚀

2023-09-01 11:40 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      operationId: get-subscription_groups-uid-prepayments.json
listPrepaymentsForSubscriptionGroup - should start from lower case.
alternatively: listSubscriptionGroupPrepayments

2023-09-01 12:09 UTC, michalpierog requested changes
I added a few suggestion how to improve docs for code generation purposes.

2023-09-01 14:02 UTC, michalpierog approved these changes
LGTM

2023-09-01 14:07 UTC, merged