Document API for updating a component
maxio-com/stoplight-platform-api-docs pull request #211
Opened 2023-08-30 15:32 UTC by lucassus

2023-08-31 07:50 UTC, michalpierog requested changes
Looks good to me, added a few suggestion how to improve it.

2023-08-31 07:50 UTC, michalpierog commented on components/schemas/Update-Component.yaml
> +    description: "One of the following: Business Software, Consumer Software, Digital Services, Physical Goods, Other"
If this is a predefined set of allowed values please use an enum (extract to a separate file).

2023-08-31 07:50 UTC, michalpierog commented on components/schemas/Update-Component.yaml
> +    type: string # or enum?
Is this any string or some predefined values? We have a lot of inconsistencies in the doc and in most places it's plain string but there is a one place which is using Credit-Type.yaml 

Create-Allocation.yaml:
```
    $ref: "./Credit-Type.yaml"
    description: The type of charge to be created if the change in cost is an upgrade. Defaults to the component and then site setting if one is not provided.
```
and Credit-Type.yaml is defined as:
```
title: Credit Type
type: string
description: |-
  The type of credit to be created when upgrading/downgrading. Defaults to the component and then site setting if one is not provided.
  Available values: `full`, `prorated`, `none`.
enum:
  - full
  - prorated
  - none
```

If this is the same enum as enum used for creating allocations you can reuse it (and override description in Update-Component.yaml if necessary).

2023-08-31 07:50 UTC, michalpierog commented on components/schemas/Update-Component.yaml
> +  # TODO: Figure out how to dry it up
Is there anything missing? The definition looks fine so you can remove this comment.

2023-08-31 07:50 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +            application/xml:
In other places we do not add `application/xml` so just remove it to be consistent.

2023-08-31 07:50 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +      parameters: []
You can skip empty parameters.

2023-08-31 07:50 UTC, michalpierog commented on reference/Chargify-API.v1.yaml
> +        description: The id of the component
Operation description says that it's possible to use handle here? 
If it is true use `string` for the type and update description here with info about handle.

2023-09-05 12:15 UTC, lucassus commented on reference/Chargify-API.v1.yaml
> +            application/xml:
Done

2023-09-05 12:16 UTC, lucassus commented on reference/Chargify-API.v1.yaml
> +      parameters: []
Done

2023-09-05 12:29 UTC, lucassus commented on components/schemas/Update-Component.yaml
> +    type: string # or enum?
Done

2023-09-05 14:31 UTC, lucassus commented
@michalpierog thank you for the review. I applied all your suggestion, could you take another look?

2023-09-05 14:46 UTC, michalpierog approved these changes
LGTM, added one comment to reuse existing model.

2023-09-05 14:46 UTC, michalpierog commented on components/schemas/Update-Component.yaml
> +    type: string
You can probably use existing Credit-Type.yaml:
```
upgrade_charge:
   allOf:
      $ref: "./Credit-Type.yaml"
   description: "The type of charge to be applied when a component is upgraded. Valid values are: `prorated`, `full`, `none`."
```

This will reuse existing model, but override description for upgrade_charge.

2023-09-26 09:08 UTC, merged