WIP- consolidating custom content into developer portal
maxio-com/stoplight-platform-api-docs pull request #448
Opened 2024-02-21 00:07 UTC by nestorsalinas88

2024-03-01 12:55 UTC, nestorsalinas88 commented
Added pages and sections for Core Concepts, Development Tools, and Introduction side navigation. Also included the a placeholder for the marketing landing page

2024-03-01 13:07 UTC, michalpierog commented
Please fix relative links and links to generated content or links to a content in the new portal.

2024-03-01 13:07 UTC, michalpierog requested changes

2024-03-01 13:07 UTC, michalpierog commented on portal/content/core-concepts/product-catalog.md
> +Products control what is charged and how often charges are assessed/billed to a subscription. If you need help after reading this, please [let us know](./Overview.md#support) so we can help and also
Invalid link

2024-03-01 13:07 UTC, michalpierog commented on portal/content/core-concepts/product-catalog.md
> +- Creating the [product family](#product-family)
Are those relative links working fine?

2024-03-01 13:07 UTC, michalpierog commented on portal/content/core-concepts/product-catalog.md
> +That data should be posted to the [Product Family Create](https://developers.chargify.com/docs/api-docs/b3A6MTQxMDgzNDI-create-product-family) API Endpoint.
Use proper link to generated endpoint.

2024-03-01 13:07 UTC, michalpierog commented on portal/content/core-concepts/product-catalog.md
> +Please see [API Documentation](https://developers.chargify.com/docs/api-docs/b3A6MTQxMDgzMzY-create-product) for a complete listing of input/output schema, along with code examples in multiple progra
Fix link to generated endpoints.

2024-03-01 13:07 UTC, michalpierog commented on portal/content/core-concepts/product-catalog.md
> +- Creating components [via the API](https://developers.chargify.com/docs/api-docs/b3A6MTQxMDgzMjA-create-component)
Link to endpoint

2024-03-01 13:07 UTC, michalpierog commented on portal/content/core-concepts/relationship-invoicing.md
> +  - [Invoices](./b3A6MTQxMTA0MTA-read-invoice)
Invalid relative link.

2024-03-01 19:15 UTC, djdaludado commented on portal/content/core-concepts/product-catalog.md
> +Products control what is charged and how often charges are assessed/billed to a subscription. If you need help after reading this, please [let us know](./Overview.md#support) so we can help and also
Fixed relative link.

2024-03-01 19:21 UTC, djdaludado commented on portal/content/core-concepts/product-catalog.md
> +- Creating the [product family](#product-family)
Yes. Tested anchor links by reducing browser window so you don't see the given anchor heading. When you click on the anchor link, it jumps to the related heading.

2024-03-05 14:23 UTC, michalpierog approved these changes

2024-03-05 15:08 UTC, merged